helperland/HelperLand/HelperLand/Controllers/ServiceProviderController.cs
using HelperLand.Data;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using HelperLand.Models;
using HelperLand.ViewModels;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using OfficeOpenXml;
using System.IO;
using MailKit.Net.Smtp;
using MailKit;
using MimeKit;
using MailKit.Security;

namespace HelperLand.Controllers
{
    public class ServiceProviderController : Controller
    {

        private readonly HelperLandContext _helperlandContext = null;
        public ServiceProviderController(HelperLandContext helperlandContext)
        {
            _helperlandContext = helperlandContext;

        }

        public IActionResult Dashboard()
        {
            var u_name = _helperlandContext.Users
                .Where(a => a.Email == HttpContext.Session.GetString("username"))
                .Select(a => a.FirstName)
                .FirstOrDefault();
            ViewBag.name = u_name;

            return View();
        }

        [HttpGet]
        public IActionResult NewServiceTable()
        {

            var id = _helperlandContext.Users
               .Where(a => a.Email == HttpContext.Session.GetString("username"))
               .Select(a => a.UserId)
               .FirstOrDefault();

            var spZipcode = _helperlandContext.UserAddresses
                .Where(a => a.UserId == id)
                .Select(a => a.PostalCode)
                .FirstOrDefault();

            List<ServiceRequest> newService = _helperlandContext.ServiceRequests
                .Where(a => a.ZipCode == spZipcode && a.Status == null)
                .ToList();

            foreach (var item in newService)
            {
                _helperlandContext.Entry(item).Reference(s => s.User).Load();
                _helperlandContext.Entry(item).Collection(s => s.ServiceRequestAddresses).Load();
            }

            return View(newService);
        }

        [HttpPost]
        public JsonResult AcceptService(int Id)
        {
            var service = _helperlandContext.ServiceRequests
                .Where(a => a.ServiceRequestId == Id)
                .FirstOrDefault();

            var id = _helperlandContext.Users
              .Where(a => a.Email == HttpContext.Session.GetString("username"))
              .Select(a => a.UserId)
              .FirstOrDefault();


            if (service != null )
            {
                // if (service != null && service.ProvicderId == null )
                List<ServiceRequest> spService = _helperlandContext.ServiceRequests
                       .Where(a => a.ServiceProviderId == id)
                       .ToList();

                foreach (var item in spService)
                {

                    if (item.ServiceStartDate.ToLongDateString() == service.ServiceStartDate.ToLongDateString())
                    {
                        int result = DateTime.Compare(item.ServiceStartDate.AddHours(Convert.ToDouble(item.ServiceHours + item.ExtraHours)), service.ServiceStartDate);

                        if (result < 0)
                        {
                            service.Status = 1;
                            service.ServiceProviderId = id;
                            service.SpacceptedDate = DateTime.Now;
                            _helperlandContext.Update(service);
                            _helperlandContext.SaveChanges();
                            return Json(true);
                        }

                        else
                        {
                            return Json(false);
                        }
                    }
                    //}
                }

                if (service.ServiceProviderId == null)
                {
                    service.Status = 1;
                    service.ServiceProviderId = id;
                    service.SpacceptedDate = DateTime.Now;
                    _helperlandContext.Update(service);
                    _helperlandContext.SaveChanges();

                    for (int i = 0; i <= _helperlandContext.Users.Count(); i++)
                    {
                        var SpInArea = _helperlandContext.Users
                            .Where(a => a.UserTypeId == 2 && a.ZipCode == service.ZipCode)
                            .Select(a => a.Email)
                            .FirstOrDefault();

                        MimeMessage message = new MimeMessage();
                        message.From.Add(new MailboxAddress("Helperland", "helperlandservice@gmail.com"));
                        message.To.Add(MailboxAddress.Parse(SpInArea));
                        message.Subject = "Service Acceptance";
                        string host = $"{HttpContext.Request.Scheme}://{HttpContext.Request.Host}";

                        message.Body = new TextPart("html")
                        {

                            Text = "The service with ID:" + Id + " is Accepted by  someone and is no more available to you."

                        };

                        SmtpClient smtp = new SmtpClient();
                        try
                        {
                            smtp.Connect("smtp.gmail.com", 587, SecureSocketOptions.StartTls);
                            smtp.Authenticate("helperlandservice@gmail.com", "Password@33");
                            smtp.Send(message);

                        }
                        catch (Exception er)
                        {
                            Console.WriteLine(er.Message);
                        }
                        finally
                        {
                            smtp.Disconnect(true);
                            smtp.Dispose();
                        }
                    }
                    return Json(true);
                }

                //else if (service.ServiceProviderId != null)
                //{
                   
            }
            return Json(true);
        }

        public IActionResult UpcomingServiceTable()
        {

            var id = _helperlandContext.Users
                .Where(a => a.Email == HttpContext.Session.GetString("username"))
                .Select(a => a.UserId)
                .FirstOrDefault();


            List<ServiceRequest> newService = _helperlandContext.ServiceRequests
                .Where(a => a.ServiceProviderId == id && a.Status == 1)
                .ToList();

            foreach (var item in newService)
            {
                _helperlandContext.Entry(item).Reference(s => s.User).Load();
                _helperlandContext.Entry(item).Collection(s => s.ServiceRequestAddresses).Load();
            }

            return View(newService);
        }

        [HttpPost]
        public JsonResult CompleteService(int Id)
        {
            var id = _helperlandContext.Users
               .Where(a => a.Email == HttpContext.Session.GetString("username"))
               .Select(a => a.UserId)
               .FirstOrDefault();

            var service = _helperlandContext.ServiceRequests
                .Where(a => a.ServiceRequestId == Id)
                .FirstOrDefault();

            if (service != null)
            {
                service.Status = 2;
                service.ModifiedDate = DateTime.Now;
                service.ModifiedBy = id;
                _helperlandContext.Update(service);
                _helperlandContext.SaveChanges();

                var userId = _helperlandContext.ServiceRequests
                    .Where(a => a.ServiceRequestId == Id)
                    .Select(a => a.UserId)
                    .FirstOrDefault();

                var userEmail = _helperlandContext.Users
                    .Where(a => a.UserId == userId)
                    .Select(a => a.Email)
                    .FirstOrDefault();

                MimeMessage message = new MimeMessage();
                message.From.Add(new MailboxAddress("Helperland", "helperlandservice@gmail.com"));
                message.To.Add(MailboxAddress.Parse(userEmail));
                message.Subject = "Service Completion";
                string host = $"{HttpContext.Request.Scheme}://{HttpContext.Request.Host}";

                message.Body = new TextPart("html")
                {

                    Text = "Dear User service with ID:" + Id + " is Completed by Service Provider."

                };

                SmtpClient smtp = new SmtpClient();
                try
                {
                    smtp.Connect("smtp.gmail.com", 587, SecureSocketOptions.StartTls);
                    smtp.Authenticate("helperlandservice@gmail.com", "Password@33");
                    smtp.Send(message);

                }
                catch (Exception er)
                {
                    Console.WriteLine(er.Message);
                }
                finally
                {
                    smtp.Disconnect(true);
                    smtp.Dispose();
                }
            }
            return Json(true);

        }

        [HttpPost]
        public JsonResult CancelService(int Id)
        {
            var id = _helperlandContext.Users
               .Where(a => a.Email == HttpContext.Session.GetString("username"))
               .Select(a => a.UserId)
               .FirstOrDefault();

            var service = _helperlandContext.ServiceRequests
                .Where(a => a.ServiceRequestId == Id)
                .FirstOrDefault();

            if (service != null)
            {
                service.Status = 0;
                service.ModifiedDate = DateTime.Now;
                service.ModifiedBy = id;
                _helperlandContext.Update(service);
                _helperlandContext.SaveChanges();

                var userId = _helperlandContext.ServiceRequests
                    .Where(a => a.ServiceRequestId == Id)
                    .Select(a => a.UserId)
                    .FirstOrDefault();

                var userEmail = _helperlandContext.Users

helperland/HelperLand/HelperLand/Views/ServiceProvider/BlockCustomer.cshtml
<link rel="stylesheet" href="https://cdn.datatables.net/1.11.3/css/jquery.dataTables.min.css">
@{
    Layout = null;
}
@model IEnumerable<HelperLand.Models.User>

@foreach (var item in Model)
{
    <div class="d-flex justify-content-start">
        <div class="block-cust">
            <label class="fav-pro">
                <img src="~/images/cap.png">
            </label>
            <h6 class="text-left">@item.FirstName @item.LastName</h6>
            <button type="button" class="select-pro-btn" value="@item.UserId" onclick="BlockCustomer(this.value)">Block</button>
        </div>
    </div>
}




<script type="text/javascript">

    function BlockCustomer(userId) {
        $.post("/ServiceProvider/BlockCustomer", { targetId: parseInt(userId) },
            function (data) {
                if (data) {
                    alert("You blocked customer successfully");
                }
                else {
                    alert("Something went wrong!!");
                }
            });
    }

</script>

helperland/HelperLand/HelperLand/Views/ServiceProvider/Dashboard.cshtml
@{
    ViewData["Title"] = "Dashboard";
    Layout = "~/Views/Shared/_Layout1.cshtml";
}

<section class="name-container text-align-center">
    <div class="container-fluid ">
        <h1>Welcome <b>@ViewBag.name</b></h1>
    </div>
</section>

<section>
    @if (TempData["serviceAccepteError"] != null)
    {
        <div class="container d-flex justify-content-center">
            <div class="alert alert-success col-lg-6 alert1">
                <button type="button" class="close" data-dismiss="alert">&times;</button>
                <strong>@TempData["serviceAccepteError"]</strong>
            </div>
        </div>
    }
    @if (TempData["serviceConcurrentError"] != null)
    {
        <div class="container d-flex justify-content-center">
            <div class="alert alert-success col-lg-6 alert1">
                <button type="button" class="close" data-dismiss="alert">&times;</button>
                <strong>@TempData["serviceConcurrentError"]</strong>
            </div>
        </div>
    }
</section>

<!--<div class="container modal-menu">-->
<!-- The Modal -->
<!--<div class="modal fade" id="collapsiblemodal">
    <div class="modal-dialog modal-sm">
        <div class="modal-content">-->
<!-- Modal Header -->
<!--<div class="modal-header">
    <div class="container">
        <div>
            <h5 class="modal-title">Welcome</h5>
        </div>
        <div>
            <p class="modal-title">User!</p>
        </div>
    </div>
    <button type="button" class="close" data-dismiss="modal">&times;</button>
</div>-->
<!-- Modal body -->
<!--<div class="modal-body">
    <div class="container">

        <a href="#">Dashboard</a>
        <a href="#">New Service Request</a>
        <a href="#" class="active">Upcoming Service</a>
        <a href="#">Service Schedule</a>
        <a href="#">Service History</a>
        <a href="#">My Rating</a>
        <a href="#">Block Customer</a>
        <a href="#">My Setting</a>
        <a href="#"></a>

    </div>
</div>-->
<!-- Modal footer -->
<!--<div class="modal-footer">
                    <div class="container">
                        <a href="#">Prices & Services</a>
                        <a href="#">Warranty</a>
                        <a href="#">Blog</a>
                        <a href="#">Content</a>
                    </div>
                </div>

                <div class="modal-footer">
                    <div class="container" style="display: flex;margin: auto;justify-content: space-around;">
                        <a href="#"><img src="~/images/ic-facebook.png"></a>
                        <a href="#"><img src="~/images/ic-instagram.png"></a>
                    </div>
                </div>

            </div>
        </div>
    </div>

</div>-->

<div class="d-flex flex-row horizontal-menu flex-wrap">

    <a href="#" id="newServiceTab1" class="active">New Service Request</a>

    <a href="#" id="upcomingServiceTab1">Upcoming Service</a>

    <a href="#" id="serviceHistoryTab1">Service History</a>

    <a href="#" id="myRatingTab1">My Ratings</a>

    <a href="#" id="blockCustomerTab1">Block Customer</a>

</div>

<section class="left-side-menu">

    <div class="container-fluid">

        <div class="row">
            <!-- <div class="col-lg-3 col-xl-3 col-md-3 col-sm-3 col-3 table-responsive menu service-tabs"> -->
            <div class="col-lg-3 menu remove">

                <a href="#" id="newServiceTab" class="active">New Service Request</a>

                <a href="#" id="upcomingServiceTab">Upcoming Service</a>

                <a href="#" id="serviceHistoryTab">Service History</a>

                <a href="#" id="myRatingTab">My Ratings</a>

                <a href="#" id="blockCustomerTab">Block Customer</a>


            </div>
            @*<div class="col-lg-3 menu remove" style="min-height:500px">

                <a href="#" id="newServiceTab" class="active">New Service Request</a>

                <a href="#" id="upcomingServiceTab">Upcoming Service</a>

                <a href="#" id="serviceHistoryTab">Service History</a>

                <a href="#" id="myRatingTab">My Ratings</a>

                <a href="#" id="blockCustomerTab">Block Customer</a>

            </div>*@

            <div class="col-lg-9 table-responsive service-details" id="newService">
                <div class="btn-group ">
                    <p style="color: #646464;font-family: Roboto;font-weight: bold;font-size: 22px;">New Service Request</p>
                </div>

                <div id="loadNewServices">

                </div>

            </div>


            <div class="col-lg-9 table-responsive service-details" id="upcomingService">
                <div class="btn-group ">
                    <p style="color: #646464;font-family: Roboto;font-weight: bold;font-size: 22px;">Upcoming Service Request</p>
                </div>

                <div id="loadUpcomingServices">

                </div>


            </div>

            <div class="col-lg-9 table-responsive service-details" id="serviceHistory">
                <div class="d-flex justify-content-between">
                    <p style="color: #646464;font-family: Roboto;font-weight: bold;font-size: 22px;">Service History</p>
                    @using (Html.BeginForm("Export", "ServiceProvider", FormMethod.Post))
                    {
                        <input class="export-btn float-right excel" type="submit" value="Export" />
                    }
                </div>

                <div id="loadServiceHistory">

                </div>


            </div>

            <div class="col-lg-9 table-responsive service-details" id="myRating">
                <div class="btn-group ">
                    <p style="color: #646464;font-family: Roboto;font-weight: bold;font-size: 22px;">My Rating</p>
                </div>

                <div id="loadMyRating">

                </div>


            </div>

            <div class="col-lg-9 table-responsive service-details" id="blockCustomer">
                <div class="btn-group ">
                    <p style="color: #646464;font-family: Roboto;font-weight: bold;font-size: 22px;">Block Customer</p>
                </div>

                <div id="loadBlockCustomer">

                </div>


            </div>

        </div>
    </div>
    <a href="#top" class="to-top">
        <img src="~/images/up-aero.png">
    </a>
</section>

<script type="text/javascript">

    $('#upcomingService').hide();
    $('#serviceHistory').hide();
    $('#myRating').hide();
    $('#blockCustomer').hide();

    $('#newServiceTab').click(function () {
        $('#loadNewServices').load('/ServiceProvider/NewServiceTable');
        $('#upcomingService').hide();
        $('#serviceHistory').hide();
        $('#myRating').hide();
        $('#blockCustomer').hide();
        $('#newService').show();
        $('#upcomingServiceTab').removeClass('active');
        $('#serviceHistoryTab').removeClass('active');
        $('#myRatingTab').removeClass('active');
        $('#blockCustomerTab').removeClass('active');
        $('#newServiceTab').addClass('active');
    });
    $('#upcomingServiceTab').click(function () {
        $('#loadUpcomingServices').load('/ServiceProvider/UpcomingServiceTable');
        $('#newService').hide();
        $('#serviceHistory').hide();
        $('#myRating').hide();
        $('#blockCustomer').hide();
        $('#upcomingService').show();
        $('#newServiceTab').removeClass("active");
        $('#serviceHistoryTab').removeClass("active");
        $('#myRatingTab').removeClass('active');
        $('#blockCustomerTab').removeClass('active');
        $('#upcomingServiceTab').addClass("active");
    });
    $('#serviceHistoryTab').click(function () {
        $('#loadServiceHistory').load('/ServiceProvider/ServiceHistoryTable');
        $('#newService').hide();
        $('#upcomingService').hide();
        $('#myRating').hide();
        $('#blockCustomer').hide();
        $('#serviceHistory').show();
        $('#newServiceTab').removeClass("active");
        $('#upcomingServiceTab').removeClass("active");
        $('#myRatingTab').removeClass('active');
        $('#blockCustomerTab').removeClass('active');
        $('#serviceHistoryTab').addClass("active");
    });
    $('#myRatingTab').click(function () {
        $('#loadMyRating').load('/ServiceProvider/MyRatingTable');
        $('#newService').hide();
        $('#upcomingService').hide();
        $('#serviceHistory').hide();
        $('#blockCustomer').hide();
        $('#myRating').show();
        $('#newServiceTab').removeClass("active");
        $('#upcomingServiceTab').removeClass("active");
        $('#serviceHistoryTab').removeClass("active");
        $('#blockCustomerTab').removeClass('active');
        $('#myRatingTab').addClass('active');
    });
    $('#blockCustomerTab').click(function () {
        $('#loadBlockCustomer').load('/ServiceProvider/BlockCustomer');
        $('#newService').hide();
        $('#upcomingService').hide();
        $('#serviceHistory').hide();
        $('#myRating').hide();
        $('#blockCustomer').show();
        $('#newServiceTab').removeClass("active");
        $('#upcomingServiceTab').removeClass("active");
        $('#serviceHistoryTab').removeClass("active");
        $('#myRatingTab').removeClass('active');
        $('#blockCustomerTab').addClass('active');
    });

    $('#newServiceTab1').click(function () {
        $('#loadNewServices').load('/ServiceProvider/NewServiceTable');
        $('#upcomingService').hide();
        $('#serviceHistory').hide();
        $('#myRating').hide();
        $('#blockCustomer').hide();
        $('#newService').show();
        $('#upcomingServiceTab1').removeClass('active');
        $('#serviceHistoryTab1').removeClass('active');
        $('#myRatingTab1').removeClass('active');
        $('#blockCustomerTab1').removeClass('active');
        $('#newServiceTab1').addClass('active');
    });
    $('#upcomingServiceTab1').click(function () {
        $('#loadUpcomingServices').load('/ServiceProvider/UpcomingServiceTable');
        $('#newService').hide();
        $('#serviceHistory').hide();
        $('#myRating').hide();
        $('#blockCustomer').hide();
        $('#upcomingService').show();
        $('#newServiceTab1').removeClass("active");
        $('#serviceHistoryTab1').removeClass("active");
        $('#myRatingTab1').removeClass('active');
        $('#blockCustomerTab1').removeClass('active');
        $('#upcomingServiceTab1').addClass("active");
    });
    $('#serviceHistoryTab1').click(function () {
        $('#loadServiceHistory').load('/ServiceProvider/ServiceHistoryTable');
        $('#newService').hide();
        $('#upcomingService').hide();
        $('#myRating').hide();
        $('#blockCustomer').hide();
        $('#serviceHistory').show();
        $('#newServiceTab1').removeClass("active");
        $('#upcomingServiceTab1').removeClass("active");
        $('#myRatingTab1').removeClass('active');
        $('#blockCustomerTab1').removeClass('active');
        $('#serviceHistoryTab1').addClass("active");
    });
    $('#myRatingTab1').click(function () {
        $('#loadMyRating').load('/ServiceProvider/MyRatingTable');
        $('#newService').hide();
        $('#upcomingService').hide();
        $('#serviceHistory').hide();
        $('#blockCustomer').hide();
        $('#myRating').show();
        $('#newServiceTab1').removeClass("active");
        $('#upcomingServiceTab1').removeClass("active");
        $('#serviceHistoryTab1').removeClass("active");
        $('#blockCustomerTab1').removeClass('active');
        $('#myRatingTab1').addClass('active');
    });
    $('#blockCustomerTab1').click(function () {
        $('#loadBlockCustomer').load('/ServiceProvider/BlockCustomer');
        $('#newService').hide();
        $('#upcomingService').hide();
        $('#serviceHistory').hide();
        $('#myRating').hide();
        $('#blockCustomer').show();
        $('#newServiceTab1').removeClass("active");
        $('#upcomingServiceTab1').removeClass("active");
        $('#serviceHistoryTab1').removeClass("active");
        $('#myRatingTab1').removeClass('active');
        $('#blockCustomerTab1').addClass('active');
    });
</script>

helperland/HelperLand/HelperLand/Views/ServiceProvider/MyRatingTable.cshtml
<link rel="stylesheet" href="https://cdn.datatables.net/1.11.3/css/jquery.dataTables.min.css">
@{
    Layout = null;
}
@model IEnumerable<HelperLand.Models.ServiceRequest>


<table class="table service-table table-hover table-responsive-xl" id="example2">
    <thead>
        <tr>
            <th class="table-heading">Service Id </th>
            <th class="table-heading">Service Date </th>
            <th class="table-heading">Customer Name  </th>
            <th class="table-heading">Rating  </th>
            <th class="table-heading">Customer Comment  </th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {

            var time = item.ServiceStartDate.AddHours(Convert.ToDouble(item.ServiceHours + item.ExtraHours)).ToString("HH:mm");
        <tr>
            <td>
                @item.ServiceRequestId
            </td>
            <td>
                <div>
                    <span><img src="~/images/calendar2.png"></span>  <b>@item.ServiceStartDate.ToString("dd/MM/yyyy") </b>
                </div>
                <div>
                    <span><img src="~/images/layer-14.png"></span>  @item.ServiceStartDate.ToString("HH:mm") - @time
                </div>
            </td>
            <td>
                <div>
                    @item.User.FirstName @item.User.LastName
                </div>
            </td>
            <td>
                @if (item.Ratings != null)
                {
                    @foreach (var a in item.Ratings)
                    {
                        <span>Ratings:</span> @a.Ratings
            <div class="row">
                @for (var i = 0; i < a.Ratings; i++)
                {

                <div class="col-lg-1">
                    <span><img src="~/images/star1.png" /></span>
                </div>

                }
            </div>
                            }
                            }
                        </td>
            <td>
                @if (item.Ratings != null)
                {
                    @foreach (var a in item.Ratings)
                    {
                        @a.Comments
                    }
                }
            </td>
        </tr>

        }

    </tbody>
</table>


<script type="text/javascript">

    $(document).ready(function () {
        $('#example2').DataTable();
    });

</script>

helperland/HelperLand/HelperLand/Views/ServiceProvider/SpAddress.cshtml
@model UserAddress
@{
    Layout = null;
}

<div class="basic_detail">
    <p><b>My Address</b></p>
</div>
<hr />

<form class="form-section" method="post" action="@Url.Action("SpAddress","ServiceProvider")">
    <div class="row justify-content-left form-group">

        <div class="col-lg-4 col-md-4">
            <div class="form-group">
                <input type="hidden" asp-for="AddressId" />
                <label>Street Name</label>
                <input type="text" class="form-control" placeholder="Enter Street Name" id="street" asp-for="AddressLine1">
                <span asp-validation-for="AddressLine1" class="text-danger"></span>
            </div>
        </div>
        <div class="col-lg-4 col-md-4">
            <div class="form-group">
                <label>House Number</label>
                <input type="text" class="form-control" placeholder="Enter House Number" id="house_no" asp-for="AddressLine2">
                <span asp-validation-for="AddressLine2" class="text-danger"></span>
            </div>
        </div>
        <div class="col-lg-4 col-md-4">
            <div class="form-group">
                <label>Postal code</label>
                <input type="text" class="form-control" placeholder="Enter Postalcode" id="postalcode" asp-for="PostalCode">
                <span asp-validation-for="PostalCode" class="text-danger"></span>
            </div>
        </div>
    </div>

    <div class="row justify-content-left form-group">

        <div class="col-lg-4 col-md-4">
            <div class="form-group">
                <label>City</label>
                <input type="text" class="form-control" placeholder="Enter City" id="city" asp-for="City">
                <span asp-validation-for="City" class="text-danger"></span>
            </div>
        </div>
    </div>
    <div class="text-center">
        <div class="row justify-content-left">
            <button class="check-zip-btn" formmethod="post">Save</button>
        </div>
    </div>
    </form>

helperland/HelperLand/HelperLand/Views/ServiceProvider/SpPassword.cshtml
@{
    Layout = null;
}
@model UserViewModel

<div class="basic_detail">
    <p><b>Change Password</b></p>
</div>
<hr />

<form method="post" action="@Url.Action("SpPassword","ServiceProvider")">
    <div class="row">
        <div class="col-lg-4">
            <div class="form-group">
                <label> Old Password</label>
                <input class="form-control" type="password" placeholder="Current Password" asp-for="OldPassword">
                <span asp-validation-for="OldPassword" class="text-danger"></span>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-lg-4">
            <div class="form-group">
                <label> New Password</label>
                <input class="form-control" type="password" placeholder="New Password" asp-for="Password">
                <span asp-validation-for="Password" class="text-danger"></span>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-lg-4">
            <div class="form-group">
                <label> Confirm Password</label>
                <input class="form-control" type="password" placeholder="Confirm Password" asp-for="ConfirmPassword">
                <span asp-validation-for="ConfirmPassword" class="text-danger"></span>
            </div>
        </div>
    </div>

    <div class="row">
        <div class="mt-2">
            <button type="submit" class="check-zip-btn" formmethod="post">Save</button>
        </div>
    </div>
</form>

<script src="~/js/site.js"></script>
<script src="~/lib/jquery/dist/jquery.js"></script>
<script src="~/lib/jquery-validation/dist/jquery.validate.js"></script>
<script src="~/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.js"></script>